COIN:
    name:           Tokugawa
    acronym:        TOK
    decimals:       6
    explorer_url:   http://explorer.tokugawacoin.com/ext/getaddress/

MASTERNODES:
    - name:           MN01
      setup_date:     27/08/2018
      setup_balance:  2500
      address:        TbP5rmPKGbKczVo3bR7qDk5z6YVN2N3hJA

    - name:           MN02
      setup_date:     27/08/2018
      setup_balance:  2500
      address:        TrWZwDC5qVhSz92wTYGo1QbpZayPu3NKik

    - name:           MN03
      setup_date:     27/08/2018
      setup_balance:  2500
      address:        TojPwoewgNJZWwazQyojCey8dKwSZYQzqC

    - name:           MN04
      setup_date:     27/08/2018
      setup_balance:  2500
      address:        TiCLkMYy5PGT3oCBypaBgjfN6WkSJtufyt

    - name:           MN05
      setup_date:     27/08/2018
      setup_balance:  2500
      address:        TaB8NZnd92B1jJjxn567S9YroeAYf1LC4E

    - name:           MN06
      setup_date:     27/08/2018
      setup_balance:  2500
      address:        Tc5CLGBGJYdjjLnPmTmQ8ZUo9nbpsUYQUX

    - name:           MN07
      setup_date:     27/08/2018
      setup_balance:  2500
      address:        TvNNBWqSE12yfGtucUszA8WfQTNsZzNMaU

    - name:           MN08
      setup_date:     27/08/2018
      setup_balance:  2500
      address:        TfGaZcxcDKbFqa9N1WRRfU6A3KWKcRvff2

#THESE ADDRESSES WILL BE LISTED IN BALANCE BUT NOT TAKEN INTO ACCOUNT FOR PERFORMANCE
#SINCE THEY ARE NOT ATTACHED TO ANY MASTERNODE
OTHER_ADDRESSES:
    - name:           PERS
      address:        TjrQBaaCPoVW9mPAZHPfVx9JJCq7yZ7QnA

DISCORD:
    api_key:          123456789example
