COIN:
    name:           Smartcash
    acronym:        SMART
    decimals:       8
    explorer_url:   https://insight.smartcash.cc/api/addr/

MASTERNODES:
    - name:           MN01
      setup_date:     29/07/2018
      setup_balance:  10096.26363000
      address:        Sdu8FKa3yWNe3wXQv1qGu64XnvT89vprnK

#THESE ADDRESSES WILL BE LISTED IN BALANCE BUT NOT TAKEN INTO ACCOUNT FOR PERFORMANCE
#SINCE THEY ARE NOT ATTACHED TO ANY MASTERNODE
OTHER_ADDRESSES:
    - name:           PERS
      address:        SMqCeDfuxWQD2MgTYzdoN7ijkfKGtZvEUZ

DISCORD:
    api_key:          123456789example